{
  "path": "java.security.cert",
  "name": "CertPathValidatorException",
  "values": [
    {
      "type": "ctor",
      "ctor": "<init>()\n            Creates a CertPathValidatorException with no detail message."
    },
    {
      "type": "ctor",
      "ctor": "<init>(msg: String!)\n            Creates a CertPathValidatorException with the given detail message."
    },
    {
      "type": "ctor",
      "ctor": "<init>(cause: Throwable!)\n            Creates a CertPathValidatorException that wraps the specified throwable."
    },
    {
      "type": "ctor",
      "ctor": "<init>(msg: String!, cause: Throwable!)\n            Creates a CertPathValidatorException with the specified detail message and cause."
    },
    {
      "type": "ctor",
      "ctor": "<init>(msg: String!, cause: Throwable!, certPath: CertPath!, index: Int)\n            Creates a CertPathValidatorException with the specified detail message, cause, certification path, and index."
    },
    {
      "type": "ctor",
      "ctor": "<init>(msg: String!, cause: Throwable!, certPath: CertPath!, index: Int, reason: CertPathValidatorException.Reason!)\n            Creates a CertPathValidatorException with the specified detail message, cause, certification path, index, and reason."
    },
    {
      "type": "method",
      "status": "public"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "CertPath",
      "code": "getCertPath()",
      "desc": "Returns the certification path that was being validated when the exception was thrown.",
      "symbol": "!"
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "Int",
      "code": "getIndex()",
      "desc": "Returns the index of the certificate in the certification path that caused the exception to be thrown."
    },
    {
      "type": "method",
      "status": "public",
      "keyword": "open",
      "identifier": "CertPathValidatorException.Reason",
      "code": "getReason()",
      "desc": "Returns the reason that the validation failed.",
      "symbol": "!"
    },
    {
      "type": "nested-classes"
    },
    {
      "type": "nested-classes",
      "code": "BasicReason",
      "desc": "The BasicReason enumerates the potential reasons that a certification path of any type may be invalid."
    },
    {
      "type": "nested-classes",
      "keyword": "abstract",
      "code": "Reason",
      "desc": "The reason the validation algorithm failed."
    }
  ]
}